"""Agregar estatus_pago a pedidos

Revision ID: 3b929c0644ec
Revises: ec23e5b5f564
Create Date: 2025-04-30 20:44:04.917620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b929c0644ec'
down_revision: Union[str, None] = 'ec23e5b5f564'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('estatus_pago', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidos', 'estatus_pago')
    # ### end Alembic commands ###
