"""Create clientes and direcciones tables

Revision ID: 3bd97092dd0e
Revises: 
Create Date: 2025-04-18 20:08:16.298859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bd97092dd0e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('razon_social', sa.String(length=100), nullable=True),
    sa.Column('rfc', sa.String(length=13), nullable=True),
    sa.Column('telefono', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('tipo_pago', sa.String(length=50), nullable=True),
    sa.Column('es_habilitado', sa.Boolean(), nullable=True),
    sa.Column('fua', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_table('secciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_secciones_id'), 'secciones', ['id'], unique=False)
    op.create_index(op.f('ix_secciones_nombre'), 'secciones', ['nombre'], unique=False)
    op.create_table('direcciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('calle', sa.String(length=255), nullable=True),
    sa.Column('numero_exterior', sa.String(length=50), nullable=True),
    sa.Column('numero_interior', sa.String(length=50), nullable=True),
    sa.Column('colonia', sa.String(length=100), nullable=True),
    sa.Column('municipio', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=100), nullable=True),
    sa.Column('codigo_postal', sa.String(length=10), nullable=True),
    sa.Column('pais', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_direcciones_id'), 'direcciones', ['id'], unique=False)
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=True),
    sa.Column('precio', sa.Float(), nullable=True),
    sa.Column('precioExpress', sa.Float(), nullable=True),
    sa.Column('tipo', sa.String(length=5), nullable=True),
    sa.Column('esActivo', sa.Boolean(), nullable=True),
    sa.Column('fua', sa.DateTime(), nullable=True),
    sa.Column('seccion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['seccion_id'], ['secciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productos_id'), 'productos', ['id'], unique=False)
    op.create_index(op.f('ix_productos_nombre'), 'productos', ['nombre'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_productos_nombre'), table_name='productos')
    op.drop_index(op.f('ix_productos_id'), table_name='productos')
    op.drop_table('productos')
    op.drop_index(op.f('ix_direcciones_id'), table_name='direcciones')
    op.drop_table('direcciones')
    op.drop_index(op.f('ix_secciones_nombre'), table_name='secciones')
    op.drop_index(op.f('ix_secciones_id'), table_name='secciones')
    op.drop_table('secciones')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
