"""Actualización del modelo Producto

Revision ID: 7e851cb3e6b6
Revises: 9dc8f18ceeaa
Create Date: 2025-04-14 20:28:01.799219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7e851cb3e6b6'
down_revision: Union[str, None] = '9dc8f18ceeaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('precioExpress', sa.Float(), nullable=True))
    op.add_column('productos', sa.Column('tipo', sa.String(length=5), nullable=True))
    op.add_column('productos', sa.Column('esActivo', sa.Boolean(), nullable=True))
    op.add_column('productos', sa.Column('fua', sa.DateTime(), nullable=True))
    op.alter_column('productos', 'nombre',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('productos', 'nombre',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('productos', 'fua')
    op.drop_column('productos', 'esActivo')
    op.drop_column('productos', 'tipo')
    op.drop_column('productos', 'precioExpress')
    # ### end Alembic commands ###
