"""Relacion  entre Sección y Producto

Revision ID: 9dc8f18ceeaa
Revises: df73104ac861
Create Date: 2025-04-10 21:04:45.466204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dc8f18ceeaa'
down_revision: Union[str, None] = 'df73104ac861'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('seccion_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'productos', 'secciones', ['seccion_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'productos', type_='foreignkey')
    op.drop_column('productos', 'seccion_id')
    # ### end Alembic commands ###
