"""aumentar precisión a 4 decimales

Revision ID: ec23e5b5f564
Revises: 596141342c58
Create Date: 2025-04-29 21:36:16.393892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ec23e5b5f564'
down_revision: Union[str, None] = '596141342c58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pagos', 'monto_pagado',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.DECIMAL(precision=10, scale=4),
               existing_nullable=False)
    op.alter_column('partidas_pedido', 'precio_unitario',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.DECIMAL(precision=10, scale=4),
               existing_nullable=False)
    op.alter_column('partidas_pedido', 'importe',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.DECIMAL(precision=10, scale=4),
               existing_nullable=False)
    op.alter_column('pedidos', 'subtotal',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.DECIMAL(precision=10, scale=4),
               existing_nullable=False)
    op.alter_column('pedidos', 'descuento',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.DECIMAL(precision=10, scale=4),
               existing_nullable=False)
    op.alter_column('pedidos', 'envio',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.DECIMAL(precision=10, scale=4),
               existing_nullable=False)
    op.alter_column('pedidos', 'iva',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.DECIMAL(precision=10, scale=4),
               existing_nullable=False)
    op.alter_column('pedidos', 'total',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.DECIMAL(precision=10, scale=4),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pedidos', 'total',
               existing_type=sa.DECIMAL(precision=10, scale=4),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('pedidos', 'iva',
               existing_type=sa.DECIMAL(precision=10, scale=4),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('pedidos', 'envio',
               existing_type=sa.DECIMAL(precision=10, scale=4),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('pedidos', 'descuento',
               existing_type=sa.DECIMAL(precision=10, scale=4),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('pedidos', 'subtotal',
               existing_type=sa.DECIMAL(precision=10, scale=4),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('partidas_pedido', 'importe',
               existing_type=sa.DECIMAL(precision=10, scale=4),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('partidas_pedido', 'precio_unitario',
               existing_type=sa.DECIMAL(precision=10, scale=4),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('pagos', 'monto_pagado',
               existing_type=sa.DECIMAL(precision=10, scale=4),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
